### ISSUE TITLE
All <ul> have padding right

### ISSUE THREAD

**Issue by Obka** [PerseusTheGreat/bs4rtl-examples#1]
Hello dear ,
why every `<ul></ul>` have an padding right ? maybe mistake ! please check it ,

Thank you.

**Comment by PerseusTheGreat** [comment]
Hi @Obka.
I think it is true;
In left-to-right direction, `<ul>` has `padding-left`, in right-to-left, it should be reflected.
In RTL direction, html will be rendered from top-right to bottom-left of viewport.

**Suggestion:**
Write some LTR styles and use [rtlcss.com](https://rtlcss.com/) to convert those. Then compare LTR and RTL styles.

**Comment by Obka** [comment]
Ok, but when use the rtl direction when I use <ul> and padding-right 0 for ul this fix the padding I'm confused, please check my solution

**Comment by PerseusTheGreat** [comment]
As you know, `<ul>` will be used to create bulleted lists. In both directions (LTR and RTL), in all cultures, along side of bulleted lists, there are some spaces in start of each row that used to align bullets and first character of each row's content. `<ul>` element is a block and its bullets will be shown inside the block (like other contents). In HTML, when we want to align and format contents of an element, inside of that, we should use CSS rules including `padding`. But, when we want to use `<ul>` as a container of some items and then visualize them as something other than bulleted list, we should reset all of its default styles (including `padding`).

This is an example in LTR (because GITHUB is LTR):

- Item 1
- Item 2
- Item 3

As you see, each row has started farther than other text contents. It is because of default styles of `ul` element.

I have reviewed Original LTR Bootstrap styles. The `padding` space of `ul` element is because of default styles of browsers.

**Comment by Obka** [comment]
Ok thank you for explain
